# Generated by Django 3.2.5 on 2021-09-21 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210920_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaria',
            name='data_atendimento',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='diaria',
            name='motivo_cancelamento',
            field=models.TextField(blank=True, null=True),
        ),
    ]
