# Generated by Django 3.2.5 on 2021-11-03 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_enderecodiarista'),
        ('api', '0015_avaliacaodiaria'),
    ]

    operations = [
    ]
