# Generated by Django 3.2.5 on 2021-11-03 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0002_auto_20210802_1955'),
        ('administracao', '0004_auto_20210707_1737'),
    ]

    operations = [
    ]
